Add overview of literals
crystal-lang/crystal-book pull request #184
Opened 2017-12-29 22:27 UTC by straight-shoota

2018-01-08 18:26 UTC, mverzilli approved these changes

2018-01-09 17:09 UTC, RX14 requested changes

2018-01-09 17:09 UTC, RX14 commented on syntax_and_semantics/literals.md
> +| [Hash-like](./literals/hash.html)         | `MyType{"foo" => "bar"}`                    |
Can we link to sections here?

2018-01-09 18:08 UTC, straight-shoota commented on syntax_and_semantics/literals.md
> +| [Hash-like](./literals/hash.html)         | `MyType{"foo" => "bar"}`                    |
Great idea!

2018-01-09 18:16 UTC, asterite requested changes

2018-01-09 18:16 UTC, asterite commented on syntax_and_semantics/literals.md
> +| [Array](./literals/array.html)            | `[1, 2, 3]`, `[1, 2, 3] of Number`, `%w(one two three)` |
`[] of Number` doesn't compile

2018-01-16 18:46 UTC, RX14 approved these changes

2018-01-16 18:51 UTC, merged

2018-01-16 18:51 UTC, mverzilli commented
Thank you!